---
title: 'Benchmarking clustifyR'
date: '`r Sys.Date()`'
output:
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 3
    df_print: paged
    vignette: >
      %\VignetteIndexEntry{clustifyR-benchmark}
      %\VignetteEngine{knitr::rmarkdown}
      %\VignetteEncoding{UTF-8}
---

```{r knitr_opts, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.align = "center"
)
```

## Samples

MCA lung dataset annotation using `ref_tabula_muris_drop` reference

## Benchmark

```{r library, include = F, eval = F}
library(Seurat)
library(clustifyR)
library(tidyverse)

l1 <- read_delim("/Users/rf/Downloads/rmbatch_dge/Lung1_rm.batch_dge.txt.gz", delim = " ")
l1 <- read_delim("/Users/rf/Downloads/rmbatch_dge/Lung1_rm.batch_dge.txt.gz", delim = " ", col_names = c("id",colnames(l1)), skip = 1)

l2 <- read_delim("/Users/rf/Downloads/rmbatch_dge/Lung2_rm.batch_dge.txt.gz", delim = " ")
l2 <- read_delim("/Users/rf/Downloads/rmbatch_dge/Lung2_rm.batch_dge.txt.gz", delim = " ", col_names = c("id",colnames(l2)), skip = 1)

l3 <- read_delim("/Users/rf/Downloads/rmbatch_dge/Lung3_rm.batch_dge.txt.gz", delim = " ")
l3 <- read_delim("/Users/rf/Downloads/rmbatch_dge/Lung3_rm.batch_dge.txt.gz", delim = " ", col_names = c("id",colnames(l3)), skip = 1)

genes <- intersect(intersect(l1$id, l2$id), l3$id)

l1m <- l1 %>% column_to_rownames("id")
l2m <- l2 %>% column_to_rownames("id")
l3m <- l3 %>% column_to_rownames("id")

l1n <- l1m[genes,]
l2n <- l2m[genes,]
l3n <- l3m[genes,]

l <- cbind(l1n,l2n) %>% cbind(l3n)
l <- t(l) %>% as.matrix()

m <- read_csv("/Users/rf/Downloads/MCA_CellAssignments.csv")
m %>% filter(Cell.name %in% rownames(l)) -> l_meta
l_meta %>% column_to_rownames("Cell.name") -> l_meta
saveRDS(l_meta, "MCA_lung_meta")

l <- l[l_meta$Cell.name,]
saveRDS(l, "MCA_lung_mat")
```

```{r load, message=FALSE, warning=FALSE}
library(here)
library(clustifyR)
library(tidyverse)

l_mat <- readRDS(here("MCA_lung_mat"))
l_meta <- readRDS(here("MCA_lung_meta"))
load(here("data","ref_tabula_muris_drop.rda"))
tml_ref <- ref_tabula_muris_drop[,colnames(ref_tabula_muris_drop)[str_detect(colnames(ref_tabula_muris_drop),"-Lung")][-c(8,13)]] # find lung references, remove generic terms

# default with all genes
start <- proc.time()
res <- clustify(l_mat, 
                tml_ref, 
                l_meta, 
                cluster_col = "Annotation")

res_allgenes <- cor_to_call(res, 
                            l_meta, 
                            col = "Annotation")
end <- proc.time()
names(res_allgenes) <- c("MCA annotation", "clustifyR call", "r")

print(end - start)

print(res_allgenes, n = nrow(res_allgenes))
```

## Comparison with other methods
To do
