---
title: 'rclustr overview'
date: '`r Sys.Date()`'
output:
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 3
    vignette: >
      %\VignetteIndexEntry{rclustr-overview}
      %\VignetteEngine{knitr::rmarkdown}
      %\VignetteEncoding{UTF-8}
---

```{r knitr_opts, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.align = "center"
)
```

```{r init, echo = FALSE, message = FALSE}
library(RClusterCT)
```

## Why use RClusterCT?

## Simple Example

```{r}

# test correlation function
# remember to execute functions at the end of the document
data("pbmc4k_avg");
data("pbmc_bulk_matrix");
gene_constraints <- list(pbmc4k_vargenes, rownames(pbmc_bulk_matrix));
pbmc4k_avg <- select_gene_subset(pbmc4k_avg, gene_constraints);
pbmc_bulk_matrix <- select_gene_subset(pbmc_bulk_matrix, gene_constraints);

out <- lapply(colnames(pbmc4k_avg),
       function(x){
         per_col <- lapply(colnames(pbmc_bulk_matrix),
                function(y){
                  compute_similarity(pbmc4k_avg[,x], 
                   pbmc_bulk_matrix[,y], corr_coef,
                   method = "spearman")})
         do.call(cbind, per_col)
       })

res <- do.call(rbind, out)
rownames(res) <- colnames(pbmc4k_avg)
colnames(res) <- colnames(pbmc_bulk_matrix)
res[1:10, 1:10]
```


### Obtain p-value for similarity using a permutation test


```{r}
data("pbmc4k_matrix"); data("pbmc4k_meta"); data("pbmc4k_avg"); data("pbmc_bulk_matrix");
gene_constraints <- list(rownames(pbmc4k_avg), rownames(pbmc_bulk_matrix));
sc_expr <- select_gene_subset(pbmc4k_matrix, gene_constraints);
bulk_expr <- select_gene_subset(pbmc_bulk_matrix, gene_constraints);


dist_metrics <- c("pearson",
             "spearman",
             "cosine")

res <- lapply(dist_metrics,
      function(x){
        permutation_similarity(sc_expr, bulk_expr, pbmc4k_meta, 
                               10, corr_coef, method = x)
      })

names(res) <- dist_metrics
lapply(res, function(x) x$p_val[1:4, 1:4])
```
